### ISSUE TITLE
[EPIC 2] I, as a Manager of op1st, want to know the current interaction points, channels, landing and entry pages, so I can figure out the current status, what needs to be continued, what needs to be upgraded or downgraded.

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#135]
Persona/ User: Manager of op1st
User's Story: I want to know the current interaction points, channels, landing and entry pages
Reason: so I can figure out the current status, what needs to be continued, what needs to be upgraded or downgraded

Define Done: A full list, description, quantity and quality of all input, start, contact, communication channels, pages, sites, etc. interested people can get in touch with us (push and pull)

This epic will be solved by:

- [x] 1. https://github.com/open-services-group/community/issues/153
- [x] 2. https://github.com/open-services-group/community/issues/152
- [x] 3. https://github.com/open-services-group/community/issues/151
- [ ] 4. statistics of every node/leaf on the sitemap
- [ ] 5. statistics of other channels/connections to users/community

Additional Info:
e.g. MoSCoW

**Comment by hemajv** [comment]
We attended the Operate First Website WG meeting last week and the following were discussed which will determine how to start working on this issue moving forward:

- A new Gatsby framework already being experimented with to reflect new website changes: https://operatefirst.slack.com/archives/C036JDXAH0S/p1650551279992679
- Parallel workstreams to continue to create new content and site re-design with new template
- We will need to base all our tasks based on this new framework in place and look at the WG's existing miro board for latest and most recent changes
- Broad personas or examples of ways in which one can use Operate First is also being discussed. Inputs requested from @aakankshaduggal @hemajv @erikerlandson and other data scientists for the data scientist persona specifically
