### ISSUE TITLE
[EPIC 1] As a Visitor/ potential contributor of github repo op1st/support issues, I want to have a clean and easy to navigate list of support issues, so I can easily see what issues are currently worked on, are important and where I can contribute.

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#138]
Persona/ User: As a Visitor/ potential contributor of github repo op1st/support issues
User's Story: I want to have a clean and easy to navigate list of support issues
Reason: so I can easily see what issues are currently worked on, are important and where I can contribute.

Define Done: ...

This epic will be solved by:

- [x] https://github.com/open-services-group/community/issues/154
- [x] https://github.com/open-services-group/community/issues/155
- [x] https://github.com/open-services-group/community/issues/156
- [x] https://github.com/open-services-group/community/issues/157
- [x] https://github.com/open-services-group/community/issues/158

## Additional Info:
e.g. MoSCoW

#### affected by:
- 

#### will affect:
- https://github.com/operate-first/support

**Comment by schwesig** [comment]
Ideas from Sprint Planning 2022-04-19
- Using the new Project View from GitHub and customized columns
  - who is working on it
  - see the status
- this Project can only create tools, rules, workflows, but not maintain the discipline for the next x years

Goals can be:
find best practices
finding tools

suggest to use project board views
documentation of best ways
finding good examples already running
link to it
create an example board/template --> governance/general template

**Comment by schwesig** [comment]
see also the input from @HumairAK
