### ISSUE TITLE
[EPIC] As a service user, I want to have a one stop location to interact with the community and its developers so I can give feedback on the service

### ISSUE THREAD

**Issue by Gkrumbach07** [open-services-group/community#144]
## Persona / User

Thoth Guidance Service user

## User's Story

I want to have a one stop location to interact with the community and its developers

## Reason

so I can give feedback on the service

## Define Done

- [ ] There needs to be a central page that links to all the forms of communication with the community
- [ ] There needs to be a way to differentiate between problem issues and feedback issues 
- [ ] There should be a way to easily see requested and accepted features so duplicate issues are avoided
