### ISSUE TITLE
[EPIC] As a service user, when I open a PR,  I want to have an estimated timeline for its resolution:

### ISSUE THREAD

**Issue by Gkrumbach07** [open-services-group/community#147]
## Persona / User

Thoth Guidance Service user

## User's Story

when I open a PR, I want to have an estimated timeline for its resolution

## Reason

- So that I can have a better understanding of when any related issues will be resolved
- So that I can anticipate the amount of additional time and effort that will go in the PR and plan other tasks accordingly

## Define Done

- [ ]  https://github.com/open-services-group/community/issues/173
- [ ]  https://github.com/open-services-group/community/issues/174
- [ ]  Update the tekton pipeline github bot to comment on the org/repo decided in criterion 1

**Comment by chauhankaranraj** [comment]
Hey @Gkrumbach07, @oindrillac and I were thinking of having these as the "define done" criteria, please let us know if you have any feedback!

Define Done
- [ ] Figure out which repo/org we want to create this service for 
- [ ] Retrain models (re-engineering features if needed) on that repo/org
- [ ] Update seldon inference service to use new model
- [ ] Update the tekton pipeline github bot to comment on the org/repo decided in criterion 1

**Comment by Gkrumbach07** [comment]
Looks good. We might want to talk with @KPostOffice to see if this could be a job for Kebechet or a separate bot. I am not familiar with the bot mentioned.

**Comment by oindrillac** [comment]
Thanks! Right now the PoC service was setup as a webhook by @harshad16 which will comment on PRs such as like [this](https://github.com/harshad16/test/pull/76#issuecomment-1090827766). @KPostOffice @harshad16 please feel free to advise on where this would fit best.

**Comment by harshad16** [comment]
As this would provide a single service i.e time to merge for a PR.
It was designed to be a single tekton pipeline that can be triggered via an event listener.

I would suggest, that if there is some more feature that is in the planning stage, then we can convert this into its own GitHub app.
If we feel, we should plan for this, aicoe-ci is happy to accommodate this feature as its part till then.

This might not be a direct fit for kebechet in my opinion.

**Comment by Gkrumbach07** [comment]
Has been superseded by https://github.com/thoth-station/core/issues/425

/close
