### ISSUE TITLE
[EPIC 5][Xpt] Operate First Value ODH/RHODS/THOTH

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#184]
- [x] 1. collect Values (step one mvp, butongoing process)
- [x] 2. create (gdoc) document [gDoc link](https://docs.google.com/document/d/1L9_G4qPQwUgAd3isqDErioXo7vayDvUhyTWZtVU9Bp8/edit#heading=h.qbvr6l73b8u)
- [ ] 3. create an online jupyterbook of the gDoc
- [ ] 4. maintain and update/ grow jupyterbook

please add anybody you think could contribute here with ideas
E.g. converting the mail thread into a JupyterBook seems straight forward, it already has concrete examples
and we could link it with dynamic proof points
e.g. the JupyterHub profile analysis by @Shreyanand

maybe we can start by identifying what sort of issues/prs we consider contributing to "adding value", and then whether we have existing labels for that
also did we ever figure out a way to identify issues outside the org that are linked back to the operate-first org on github?

I think this is something @hemajv 

and obviously this is an additional ask, so it would be a user story to be put on one of the scrum boards
I guess O2KR2? @schwesig 

"Can you provide any stats about my service? Can you give me trends on users, outages, issues, consumption?"
https://grafana.operate-first.cloud/d/fuJBFErMz/jupyterhub-user-perspective?orgId=1&var-datasource=moc-smaug&var-log_datasource=app-logs&var-namespace=opf-jupyterhub&var-account=alivaster121&var-account_substring=
Is he looking for an even higher level analysis of the service operations data? (maybe trends isn't captured here)

....

**Comment by schwesig** [comment]
https://docs.google.com/document/d/1L9_G4qPQwUgAd3isqDErioXo7vayDvUhyTWZtVU9Bp8/edit
