### ISSUE TITLE
[EPIC 4] As the host of a meeting/chair of a group, I want to have a metrics/dashboard/funnel from first contact to becoming an active contributor, so I can see how and why my community grows.

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#186]
- [x] 1. create a useful funnel (blueprint)
- [x] 2. set it up for one community (Thoth or OS Climate)
- [x] 3. test it and adjust it
- [x] 4. stabilize it
- [x] 5. run it on the other (Thoth and OS Climate)
- [ ] 6. deploy it on the other communities

Questions:
e.g.
- what channels lead to my meetings (first time attendee, xth time attendee)
- what communication/content lead to my meetings (first time attendee, xth time attendee)
- what meetings create growth of followers in github
- what meetings/issues make followers to contributors
- what topics lead to a higher contribution rate
- ...

this epic should lead to the different topics above,
and for each of these communities:

- [ ] Enterprise Neurosystems
- [ ] Operate First Operations
- [ ] Open Data Hub
- [ ] OS Climate
- [ ] Project Thoth
