### ISSUE TITLE
[Xpt][EPIC] Working group agenda -  section for community focus and news exchange via e.g. blog

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#213]
open: define the user story...
maybe like:
As the community I want to be informed about decisions and possible new community things that could come from RH internal efforts.
As the working group I want to be informed what is going on in the upstream, new trends and possible new topics & ideas to work on, focus on, be prepared to.

initiated by an email Hild, Burns 2022-06-07

Basic Idea:
having a strong connection between the community and internal efforts is essential.

- [x] adding an community area to the agenda of the meetings
  - [x] Upstream community news
  - [x] Community cloud news
- [x] connecting community new to the meeting/agenda and vice versa
  - [x] maintain blog
  - [x] connect blog
