### ISSUE TITLE
[SP ComCom] +epic+ Create, establish and sustain team news stream with abstracts for every team and meeting

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#78]
epic for these issues:

- [x] 1. [[SP ComCom] NewsFlash - Create a list of all Meetings in the [OSG] Calendar #85](https://github.com/open-services-group/community/issues/85)
- [x] 2. [[SP ComCom] Create a template for notes, after- and pre-meeting #88](https://github.com/open-services-group/community/issues/88)
- [x] 3. [[SP ComCom] Schedule a group or one-on-one meeting to coach and discuss the templates for NewsFlash & notes](https://github.com/open-services-group/community/issues/89)

create a
tl;da; = too long; didn't attend;
tl;dp; = too long; didn't participate;

instead of presenting the status of every team/SIG/etc. in e.g the AllHandsMeeting, some kind of newsletter and digest should be created.
So far ideas:
for every meeting/group/team in the [OSG] calender
per meeting:
Headline/Twitter/Newsflash with link to abstract
abstract with links to the working details like issues, boards, issues, etc.

checking how much noise this will generate and maybe a clustering like a digest needs to be done.
as replacement or addition.

like: per meeting, per week, per quarter, per group, ...
the storyline per meeting/group should be established and leading through all news

**Comment by schwesig** [comment]
where to send: stay with the known channels? gchat, slack, email, ...
where to store: abstracts go ...?

**Comment by schwesig** [comment]
google docs
jupyter nb to collect and create a "log" "blog"

jupyter notebook
use sig.yaml to get the links to the notes
parse in notes: in gdoc @Meeting Notes --> between standard  Attendees: & Agenda
create a "blog" like output with header and abstract (with links)
publish it to a readme file in github

start with 2 weekly groups
- byon
- data science community meeting

gchat OSG

**Comment by durandom** [comment]
+100 for templates

But I'd also create a template for the meeting notes. Because, shouldn't the summary be a summary of the meeting? This should be captured in the meeting notes. And if it's not, then the meeting notes are missing something.

As a reader of the summary, I should be able to dive into more details, which is captured in the meeting notes and issues.

I would hold off any automation for now. It's a human task for now, which we can automate if we did it a couple of times.

So the big Q is, how do we make the human task 1) easy and less error-prone and 2) make it 2nd nature for all members of the team.

**Comment by schwesig** [comment]
> So the big Q is, how do we make the human task 1) easy and less error-prone and 2) make it 2nd nature for all members of the team.

Idea: Bot “nags” to do this
Wish: Bot asking questions, requesting the information, ... pushes to the task/note

**Comment by durandom** [comment]
It's an editoral exercise. If you (@schwesig and @codificat) cannot create a summary out of the meeting notes, then the meeting notes are bad. I.e. you have to talk to the chairs and help to fix the meeting notes, and do better next time.

Therefore I suggest to 

* create templates for meeting notes and the summary reports
* do a round-robin of the chore of writing the summary

Once we did that for some rounds, we can think about automation and bots

**Comment by schwesig** [comment]
Templates following the man pages idea:
like a newspaper: you know where to look and where to find things, no matter what day it is.
all meeting notes should have the same look, format, and best also same style/length/size of the different topics.
https://en.wikipedia.org/wiki/Man_page

**Comment by schwesig** [comment]
to solve this epic and the MVP,
I created these smaller next small steps issues here:

1. [[SP ComCom] NewsFlash - Create a list of all Meetings in the [OSG] Calendar #85](https://github.com/open-services-group/community/issues/85)
2. [[SP ComCom] Create a template for notes, after- and pre-meeting #88](https://github.com/open-services-group/community/issues/88)
3. tbd [[SP ComCom] Schedule a group or one-on-one meeting to coach and discuss the templates for NewsFlash & notes](https://github.com/open-services-group/community/issues/89)
